# Generated by Django 5.0.6 on 2024-06-06 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("qualName", models.CharField(max_length=200)),
                ("expDate", models.DateField()),
            ],
        ),
    ]
