# Generated by Django 5.0.6 on 2024-07-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_alter_profile_address_alter_profile_alt_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="photo",
            field=models.ImageField(blank=True, upload_to="users/%Y/%m/%d"),
        ),
    ]
