# Generated by Django 5.0.6 on 2024-07-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.FileField(
                blank=True,
                default="settings.MEDIA_ROOT/profile_pics/pic.png",
                null=True,
                upload_to="profile_pics",
            ),
        ),
    ]
