# Generated by Django 5.0.6 on 2024-07-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.FileField(
                blank=True, null=True, upload_to="profile_pics/pic.png"
            ),
        ),
    ]
